### PR TITLE
Split BCDMS

### PR DESCRIPTION
**Pull request by RoyStegeman**
Split BCDMS into an FKTable per Q2 to prevent troubles when merging the fktables in numerical FONLL

### CODE REVIEW

**Review by felixhekhorn — APPROVED** [review]
- I'd say also drop the old version here
- I didn't check all kinematics, but the first bins looks all fine - can you please open also a PR in yadism and change this file accordingly: https://github.com/NNPDF/yadism/blob/master/extras/data/machinery/generate/BCDMS.py ? usually we do the other way round: we first adjust yadism and then do a straight copy here

**Comment by RoyStegeman** [comment]
> I'd say also drop the old version here

Are we sure? I added them back after originally removing them since the old version is still what's used in the current theorydbs. I added a theory 450 in `NNPDF/theories_slim`: https://github.com/NNPDF/theories_slim/pull/10

> I'd say also drop the old version here
I didn't check all kinematics, but the first bins looks all fine - can you please open also a PR in yadism and change this file accordingly: https://github.com/NNPDF/yadism/blob/master/extras/data/machinery/generate/BCDMS.py ? usually we do the other way round: we first adjust yadism and then do a straight copy here

Ah I didn't know you saved the scripts used for this. I wrote my own, but will indeed update also the one in yadism. Thanks for pointing it out!

**Comment by felixhekhorn** [comment]
> Are we sure? I added them back after originally removing them since the old version is still what's used in the current theorydbs.

mmm maybe @scarlehoff has an opinion?

**Comment by scarlehoff** [comment]
I would leave them be since the next few papers will still use the old versions.

You might choose instead to tag the current version as "latest revision prior to <numerical>Fonll"

**Comment by felixhekhorn** [comment]
Actually, I just realized that here (and missing in https://github.com/NNPDF/yadism/pull/217) you also changed the `fktable_id` - but that field is completely deprecated, isn't it? @scarlehoff ?

**Comment by scarlehoff** [comment]
cc @andreab1997 @niclaurenti 

Last time I added fktables here the field still existed but that's many moons ago.

**Comment by felixhekhorn** [comment]
> cc @andreab1997 @niclaurenti
> 
> Last time I added fktables here the field still existed but that's many moons ago.

eeehm I was thinking more of the fitting side: if you are not using it there, it is deprecated

**Comment by scarlehoff** [comment]
Ah, no, it was never used from the fitting side. The fitting code only source of information is the yamldb.

**Pull request merged**
