### PR TITLE
Update pol DIS cards

### PR DESCRIPTION
**Pull request by giacomomagni**
Here we update the polarized DIS cards which are not up to date in master anymore.

### CODE REVIEW

**Review by Radonirinaunimi — COMMENTED** [review]
Thanks a lot for this @giacomomagni!! We should also include in this PR the integrability datasets for $\Delta V$ and $\Delta V_3$.

**Comment by giacomomagni** [comment]
> We should also include in this PR the integrability cards for ΔV and ΔV3.

I don't have them, could you plese commit them ?

**Review by Radonirinaunimi — APPROVED** [review]
LGTM! Thanks

**Review by felixhekhorn — APPROVED** [review]
looks fine (although I didn't check each and every one)

**Comment by felixhekhorn** [comment]
This is correlated with https://github.com/NNPDF/pinefarm/pull/78

**Pull request merged**
