### PR TITLE
Added metadata and observable runcard for EMC F2c data set

### PR DESCRIPTION
**Pull request by enocera**
This PR contains the cards to produce the pineappl grids needed for the EMC F2c data set.

### CODE REVIEW

**Review by AleCandido — APPROVED** [review]
I didn't try to run, but it looks good to me (including the [missing `arxiv` entry](https://github.com/NNPDF/pinecards/issues/136), how did you know?)

**Comment by enocera** [comment]
@AleCandido  About the (physical) correctness, I think that everything is as it should, see  https://vp.nnpdf.science/CvrNWlmeRaqy_QYdDAXMAQ==

**Comment by enocera** [comment]
About the arXiv entry, I guess that I've just looked at the other metadata cards.

**Comment by AleCandido** [comment]
> @AleCandido About the (physical) correctness, I think that everything is as it should, see
> [NNPDF/theories#3](https://github.com/NNPDF/theories/pull/3)

Yes, it is definitely reasonable (even though, if I read correctly the table, there are a lot of points that are actually compatible with 0).

**Pull request merged**
